#docker-compose -f mongodb-expressui.yml up -d
version: "3.8"

services:
  app:
    image: golang:1.21-alpine # Use the official Go image
    container_name: go_app
    working_dir: /app
    volumes:
      - ./:/app # Mount the current directory into the container
    ports:
      - "8080:8080" # Expose port 8080 for your Go app
    command: go run main.go # Run the Go application

  mongodb:
    image: mongo:latest
    container_name: abduselam-mongodb
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      #local dir/files: docker dir/files
      # iOS
      # - /Users/Admin/Documents/abduselam-arabianmejlis/web-db/mongo_db:/data/db
      # - /Users/Admin/Documents/abduselam-arabianmejlis/web-db/backup:/backup
      # Windows
      #- /c/Users/Admin/Documents/abduselam-arabianmejlis/web-db/mongo_db:/data/db
      #- /c/Users/Admin/Documents/abduselam-arabianmejlis/web-db
      # Linux
      - /home/emxnrd/devspace/abduselam-arabianmejlis/web-db/mongo_db:/data/db
      - /home/emxnrd/devspace/abduselam-arabianmejlis/web-db/backup:/backup
    ports:
      - 27017:27017
    # networks:
      # - mongo
    #echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet

  mongo-express:
    image: mongo-express:latest
    container_name: abduselam-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    volumes:
      # - /c/Users/Admin/Documents/abduselam-arabianmejlis/web-db/mongo_db
      # Linux
      - /home/emxnrd/devspace/abduselam-arabianmejlis/web-db/mongo_db:/data/db
    ports:
      - 8081:8081
    links:
      - mongodb
    # wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1

# networks:
  # mongo: # docker-compose-files_mongo
    # driver: bridge
# networks: -- To use above network services in other projects add this networks property
#  docker-compose-files_mongo: -- {{directory_name}}_{{network_name}}
#    external: true -- are you using external network?