// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "abduselam-arabianmejlis/domain"
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ProductUseCase is an autogenerated mock type for the ProductUseCase type
type ProductUseCase struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: c, product
func (_m *ProductUseCase) CreateProduct(c context.Context, product *domain.Product) (domain.Product, error) {
	ret := _m.Called(c, product)

	var r0 domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Product) (domain.Product, error)); ok {
		return rf(c, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Product) domain.Product); ok {
		r0 = rf(c, product)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Product) error); ok {
		r1 = rf(c, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: c, id
func (_m *ProductUseCase) DeleteProduct(c context.Context, id string) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProduct provides a mock function with given fields: c, id
func (_m *ProductUseCase) GetProduct(c context.Context, id string) (*domain.Product, error) {
	ret := _m.Called(c, id)

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Product, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Product); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields: c, pagination, filter
func (_m *ProductUseCase) GetProducts(c context.Context, pagination *domain.Pagination, filter interface{}) ([]*domain.Product, error) {
	ret := _m.Called(c, pagination, filter)

	var r0 []*domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Pagination, interface{}) ([]*domain.Product, error)); ok {
		return rf(c, pagination, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Pagination, interface{}) []*domain.Product); ok {
		r0 = rf(c, pagination, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Pagination, interface{}) error); ok {
		r1 = rf(c, pagination, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LikeProduct provides a mock function with given fields: c, productID, userID
func (_m *ProductUseCase) LikeProduct(c context.Context, productID string, userID string) error {
	ret := _m.Called(c, productID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(c, productID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchProducts provides a mock function with given fields: ctx, query
func (_m *ProductUseCase) SearchProducts(ctx context.Context, query string) ([]*domain.Product, error) {
	ret := _m.Called(ctx, query)

	var r0 []*domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Product, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Product); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnlikeProduct provides a mock function with given fields: c, productID, userID
func (_m *ProductUseCase) UnlikeProduct(c context.Context, productID string, userID string) error {
	ret := _m.Called(c, productID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(c, productID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProduct provides a mock function with given fields: c, product, product_id
func (_m *ProductUseCase) UpdateProduct(c context.Context, product *domain.Product, product_id string) error {
	ret := _m.Called(c, product, product_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Product, string) error); ok {
		r0 = rf(c, product, product_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProductImages provides a mock function with given fields: ctx, files, serverAdress
func (_m *ProductUseCase) UploadProductImages(ctx context.Context, files map[string]io.Reader, serverAdress string) ([]string, error) {
	ret := _m.Called(ctx, files, serverAdress)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]io.Reader, string) ([]string, error)); ok {
		return rf(ctx, files, serverAdress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]io.Reader, string) []string); ok {
		r0 = rf(ctx, files, serverAdress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]io.Reader, string) error); ok {
		r1 = rf(ctx, files, serverAdress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductUseCase creates a new instance of ProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductUseCase(t mockConstructorTestingTNewProductUseCase) *ProductUseCase {
	mock := &ProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
